services:

  siva-demo-application:
    image: siva-demo-application:latest
    ports:
      - "9000:8080"
    environment:
      - siva.service.service-host=http://siva.localhost:8080
    networks:
      default:
        aliases:
          - siva-demo.localhost
    depends_on:
      - siva-webapp

  siva-webapp:
    image: ${SIVA_DOCKER_REGISTRY}${SIVA_PROJECT}siva-webapp:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/etc/siva-webapp/application.yml
      - logging.config=/etc/siva-webapp/logback.xml
      # Logs directory
      - BUILD_FOLDER=/tmp/logs
      - "SPRING_PROFILES_ACTIVE=test"
      - TZ=Europe/Tallinn
      - t-level-signature-filter.filter-type=NOT_ALLOWED_COUNTRIES
      - t-level-signature-filter.countries=EE

    networks:
      default:
        aliases:
          - siva.localhost
    volumes:
      - ./docker/logback.xml:/etc/siva-webapp/logback.xml
      - ./docker/application.yml:/etc/siva-webapp/application.yml

  dozzle: # Web-based UI for browsing container logs
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - dozzle.localhost
    ports:
      - '11080:8080'
    restart: unless-stopped
