management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include:
          - health
          - prometheus
          # TODO: When Kubernetes is live, remove custom heartbeat endpoint if it is not used
          - heartbeat
          - version
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
    heartbeat:
      enabled: true
      cache:
        time-to-live: 10s
    version:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true

siva:
  http:
    request:
      # 20 MB + base64 overhead (ceil(20MB / 3) * 4) rounded up
      max-request-size-limit: 27MB

spring:
  autoconfigure:
    # Disable /error endpoint mapping and logging
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  web:
    resources:
      # Allow custom handler for NoHandlerFoundException
      add-mappings: false
